name: Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:

  docker_build_push_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          
      - name: Build with Maven
        run: mvn clean package

      - name: Set build number
        id: set_build_number
        run: echo "::set-output name=BUILD_NUMBER::${GITHUB_RUN_NUMBER}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t sadi1234/githubaction:${{ steps.set_build_number.outputs.BUILD_NUMBER }} .

      - name: Push Docker image to Docker Hub
        run: |
          docker push sadi1234/githubaction:${{ steps.set_build_number.outputs.BUILD_NUMBER }}

      - name: Pull Docker image from Docker Hub
        run: |
          sudo docker pull sadi1234/githubaction:${{ steps.set_build_number.outputs.BUILD_NUMBER }}

      - name: Stop and remove existing container
        run: |
          sudo docker stop your-container-name || true && docker rm your-container-name || true

      - name: Run Docker container
        run: |
          sudo docker run -d --name your-container-name -p 8080:8080 sadi1234/githubaction:${{ steps.set_build_number.outputs.BUILD_NUMBER }}

      - name: Upload WAR to S3
        id: upload_war_to_s3
        run: |
          response=$(aws s3 cp $GITHUB_WORKSPACE/web/target/*.war s3://sadi123/)
          echo "AWS SDK Response: $response"
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Copy WAR to Tmp
        run: |
          response=$(aws s3 cp s3://sadi123/Power-Cloud-1.war /tmp/)
          echo "AWS SDK Response: $response"
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy WAR to Tomcat
        run: |
          sudo mkdir -p /usr/local/tomcat/webapps/
          sudo cp $GITHUB_WORKSPACE/web/target/*.war /usr/local/tomcat/webapps/
